import { supabase } from "./supabaseClient";
import { streakFromDates, type StudentStats } from "../data/studentRewards";

// Student progress — lessons marked done and practice rounds recorded. Both tables are own-rows-only
// under RLS and only a role = 'student' account can insert (see the student_accounts migration), so
// none of these send a user_id; the column defaults to auth.uid(). Every function throws on error
// and the callers decide how loudly to fail (progress is a nice-to-have on top of the public
// pages, so most callers swallow it).

export async function getLessonsDone(): Promise<Map<string, string>> {
  const { data, error } = await supabase.from("lesson_completions").select("topic_id, completed_at");
  if (error) throw error;
  return new Map((data ?? []).map(row => [row.topic_id as string, row.completed_at as string]));
}

export async function markLessonDone(topicId: string): Promise<void> {
  const { error } = await supabase
    .from("lesson_completions")
    .upsert({ topic_id: topicId }, { onConflict: "user_id,topic_id", ignoreDuplicates: true });
  if (error) throw error;
}

export async function unmarkLessonDone(topicId: string): Promise<void> {
  const { error } = await supabase.from("lesson_completions").delete().eq("topic_id", topicId);
  if (error) throw error;
}

// `id` is generated by the caller when a round STARTS, so recording the same finished round twice
// (a double render, a retry) is a no-op instead of double XP.
export async function recordPracticeRound(round: { id: string; topics: string[]; correct: number; total: number }): Promise<void> {
  const { error } = await supabase
    .from("practice_rounds")
    .upsert({ id: round.id, topics: round.topics.slice(0, 10), correct: round.correct, total: round.total }, { onConflict: "id", ignoreDuplicates: true });
  if (error) throw error;
}

export async function getStudentStats(): Promise<StudentStats> {
  const [lessons, totals, recent, attendance] = await Promise.all([
    supabase.from("lesson_completions").select("completed_at"),
    supabase.from("my_practice_totals").select("*").maybeSingle(),
    supabase.from("practice_rounds").select("created_at").order("created_at", { ascending: false }).limit(120),
    supabase.from("class_attendance").select("day"),
  ]);
  if (lessons.error) throw lessons.error;
  if (totals.error) throw totals.error;
  if (recent.error) throw recent.error;
  // Deliberately NOT thrown: on a database without the class_membership migration this table doesn't
  // exist, and progress from lessons/practice must keep working — check-ins just count as zero.

  const activityDates = [
    ...(lessons.data ?? []).map(r => r.completed_at as string),
    ...(recent.data ?? []).map(r => r.created_at as string),
  ];
  return {
    lessonsDone: (lessons.data ?? []).length,
    rounds: (totals.data?.rounds as number | undefined) ?? 0,
    correctAnswers: (totals.data?.correct_answers as number | undefined) ?? 0,
    perfectRounds: (totals.data?.perfect_rounds as number | undefined) ?? 0,
    streakDays: streakFromDates(activityDates),
    classCheckins: attendance.error ? 0 : (attendance.data ?? []).length,
  };
}
